CREATE TABLE [dbo].[TB_ALTERNATIVA] (
    [ID]         INT           IDENTITY (1, 1) NOT NULL,
    [TEXTO]      VARCHAR (150) NOT NULL,
    [CORRETA]    BIT           NOT NULL,
    [QUESTAO_ID] INT           NOT NULL,
    CONSTRAINT [PK_ALTERNATIVA] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ALTERNATIVA_QUESTAO] FOREIGN KEY ([QUESTAO_ID]) REFERENCES [dbo].[TB_QUESTAO] ([ID])
);

