CREATE TABLE [dbo].[TB_MATERIA] (
    [ID]            INT          IDENTITY (1, 1) NOT NULL,
    [NOME]          VARCHAR (50) NOT NULL,
    [SERIE]         INT          NOT NULL,
    [DISCIPLINA_ID] INT          NOT NULL,
    CONSTRAINT [PK_MATERIA] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_TB_MATERIA_TB_DISCIPLINA] FOREIGN KEY ([DISCIPLINA_ID]) REFERENCES [dbo].[TB_DISCIPLINA] ([ID])
);



