CREATE TABLE [dbo].[TB_QUESTAO] (
    [ID]         INT           IDENTITY (1, 1) NOT NULL,
    [PERGUNTA]   VARCHAR (MAX) NOT NULL,
    [MATERIA_ID] INT           NOT NULL,
    CONSTRAINT [PK_TB_QUESTAO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MATERIA_QUESTAO] FOREIGN KEY ([MATERIA_ID]) REFERENCES [dbo].[TB_MATERIA] ([ID])
);



