CREATE TABLE [dbo].[TB_TESTE_TB_QUESTAO] (
    [ID_TESTE]   INT NOT NULL,
    [ID_QUESTAO] INT NOT NULL,
    CONSTRAINT [FK_QUESTAO_TESTE] FOREIGN KEY ([ID_QUESTAO]) REFERENCES [dbo].[TB_QUESTAO] ([ID]),
    CONSTRAINT [FK_TESTE] FOREIGN KEY ([ID_TESTE]) REFERENCES [dbo].[TB_TESTE] ([ID])
);

