USE TestesMarianaDb

DELETE FROM TB_TESTE_TB_QUESTAO
DELETE FROM TB_TESTE
DELETE FROM TB_ALTERNATIVA
DELETE FROM TB_QUESTAO
DELETE FROM TB_MATERIA
DELETE FROM TB_DISCIPLINA

DBCC CHECKIDENT(TB_TESTE, RESEED, 0)
DBCC CHECKIDENT(TB_ALTERNATIVA, RESEED, 0)
DBCC CHECKIDENT(TB_QUESTAO, RESEED, 0)
DBCC CHECKIDENT(TB_MATERIA, RESEED, 0)
DBCC CHECKIDENT(TB_DISCIPLINA, RESEED, 0)

                             
INSERT INTO TB_DISCIPLINA VALUES ('MATEMÁTICA')    
INSERT INTO TB_DISCIPLINA VALUES ('PORTUGUÊS')                
INSERT INTO TB_DISCIPLINA VALUES ('ARTES')    
INSERT INTO TB_DISCIPLINA VALUES ('CIÊNCIAS')

INSERT INTO TB_MATERIA VALUES ('Números e operações', 1,1)    
INSERT INTO TB_MATERIA VALUES ('Formas Geométricas', 2,1)     
INSERT INTO TB_MATERIA VALUES ('Vogais e consoantes', 1,2)                       
INSERT INTO TB_MATERIA VALUES ('Cores primárias', 1,3)                                    
INSERT INTO TB_MATERIA VALUES ('Animais', 1,4)  
INSERT INTO TB_MATERIA VALUES ('Plantas', 1,4)  
                
INSERT INTO TB_QUESTAO VALUES ('Qual é o resultado da adição de 3 + 2?',1)
INSERT INTO TB_ALTERNATIVA VALUES ('4',0,1)
INSERT INTO TB_ALTERNATIVA VALUES ('5',1,1)
INSERT INTO TB_ALTERNATIVA VALUES ('6',0,1)
INSERT INTO TB_ALTERNATIVA VALUES ('7',0,1)


INSERT INTO TB_QUESTAO VALUES ('Quanto é 10 - 4?',1)
INSERT INTO TB_ALTERNATIVA VALUES ('3',0,2)
INSERT INTO TB_ALTERNATIVA VALUES ('4',0,2)
INSERT INTO TB_ALTERNATIVA VALUES ('5',0,2)
INSERT INTO TB_ALTERNATIVA VALUES ('6',1,2)


INSERT INTO TB_QUESTAO VALUES ('Complete a sequência numérica: 2, 4, 6, __, 10',1)
INSERT INTO TB_ALTERNATIVA VALUES ('8',1,3)
INSERT INTO TB_ALTERNATIVA VALUES ('9',0,3)
INSERT INTO TB_ALTERNATIVA VALUES ('10',0,3)
INSERT INTO TB_ALTERNATIVA VALUES ('11',0,3)


INSERT INTO TB_QUESTAO VALUES ('Qual é o resultado da multiplicação de 5 por 3?',1)
INSERT INTO TB_ALTERNATIVA VALUES  ('8',0,4)
INSERT INTO TB_ALTERNATIVA VALUES ('12',0,4)
INSERT INTO TB_ALTERNATIVA VALUES ('15',1,4)
INSERT INTO TB_ALTERNATIVA VALUES ('18',0,4)


INSERT INTO TB_QUESTAO VALUES ('Qual é o número que vem antes do 9?',1)
INSERT INTO TB_ALTERNATIVA VALUES  ('7',0,5)
INSERT INTO TB_ALTERNATIVA VALUES  ('8',1,5)
INSERT INTO TB_ALTERNATIVA VALUES  ('9',0,5)
INSERT INTO TB_ALTERNATIVA VALUES ('10',0,5)


INSERT INTO TB_QUESTAO VALUES ('Qual das seguintes letras é uma vogal?',3)
INSERT INTO TB_ALTERNATIVA VALUES ('B',0,6)
INSERT INTO TB_ALTERNATIVA VALUES ('C',0,6)
INSERT INTO TB_ALTERNATIVA VALUES ('D',0,6)
INSERT INTO TB_ALTERNATIVA VALUES ('E',1,6)


INSERT INTO TB_QUESTAO VALUES ( 'Qual das seguintes letras não é uma vogal?',3)
INSERT INTO TB_ALTERNATIVA VALUES  ('E',0,7)
INSERT INTO TB_ALTERNATIVA VALUES ('I' ,0,7)
INSERT INTO TB_ALTERNATIVA VALUES ('F' ,1,7)
INSERT INTO TB_ALTERNATIVA VALUES ('O' ,0,7)


INSERT INTO TB_QUESTAO VALUES ('Quantas consoantes existem na palavra "Amigo"?',3)
INSERT INTO TB_ALTERNATIVA VALUES ('1',0,8)
INSERT INTO TB_ALTERNATIVA VALUES ('2',1,8)
INSERT INTO TB_ALTERNATIVA VALUES ('3',0,8)
INSERT INTO TB_ALTERNATIVA VALUES ('4',0,8)


INSERT INTO TB_QUESTAO VALUES ('Complete a palavra: "B_l_".',3)
INSERT INTO TB_ALTERNATIVA VALUES  ('Pato',   0,9)
INSERT INTO TB_ALTERNATIVA VALUES ('Bola',    1,9)
INSERT INTO TB_ALTERNATIVA VALUES ('Cachorro',0,9)
INSERT INTO TB_ALTERNATIVA VALUES ('Gato',    0,9)


INSERT INTO TB_QUESTAO VALUES ('Qual é a primeira letra do alfabeto?',3)
INSERT INTO TB_ALTERNATIVA VALUES  ('A',1,10)
INSERT INTO TB_ALTERNATIVA VALUES  ('B',0,10)
INSERT INTO TB_ALTERNATIVA VALUES  ('C',0,10)
INSERT INTO TB_ALTERNATIVA VALUES ( 'D',0,10)


INSERT INTO TB_QUESTAO VALUES ('Quais são as cores primárias?',4)
INSERT INTO TB_ALTERNATIVA VALUES ('Vermelho, verde e azul',0,11)
INSERT INTO TB_ALTERNATIVA VALUES ('Vermelho, amarelo e azul',1,11)
INSERT INTO TB_ALTERNATIVA VALUES ('Vermelho, amarelo e verde',0,11)
INSERT INTO TB_ALTERNATIVA VALUES ('Laranja, verde e roxo',0,11)


INSERT INTO TB_QUESTAO VALUES ('Misturando as cores amarelo e azul, qual cor é obtida?',4)
INSERT INTO TB_ALTERNATIVA VALUES  ('Vermelho',0,12)
INSERT INTO TB_ALTERNATIVA VALUES ('Verde' ,1,12)
INSERT INTO TB_ALTERNATIVA VALUES ('Laranja' ,0,12)
INSERT INTO TB_ALTERNATIVA VALUES ('Roxo' ,0,12)


INSERT INTO TB_QUESTAO VALUES ('Quais são as cores secundárias?',4)
INSERT INTO TB_ALTERNATIVA VALUES ('Vermelho, verde e azul',0,13)
INSERT INTO TB_ALTERNATIVA VALUES ('Vermelho, amarelo e azul',0,13)
INSERT INTO TB_ALTERNATIVA VALUES ('Vermelho, amarelo e verde',0,13)
INSERT INTO TB_ALTERNATIVA VALUES ('Laranja, verde e roxo',1,13)

INSERT INTO TB_QUESTAO VALUES ('Qual é a cor resultante da mistura das cores primárias?',4)
INSERT INTO TB_ALTERNATIVA VALUES  ('Preto',0,14)
INSERT INTO TB_ALTERNATIVA VALUES ('Branco',0,14)
INSERT INTO TB_ALTERNATIVA VALUES ('Cinza',0,14)
INSERT INTO TB_ALTERNATIVA VALUES ('Marrom',1,14)


INSERT INTO TB_QUESTAO VALUES ('Qual é a cor complementar do amarelo?',4)
INSERT INTO TB_ALTERNATIVA VALUES ( 'Roxo',1,15)
INSERT INTO TB_ALTERNATIVA VALUES  ('Azul',0,15)
INSERT INTO TB_ALTERNATIVA VALUES  ('Verde',0,15)
INSERT INTO TB_ALTERNATIVA VALUES  ('Vermelho',0,15)


INSERT INTO TB_QUESTAO VALUES ('Qual dos seguintes animais é um mamífero?',5)
INSERT INTO TB_ALTERNATIVA VALUES ('Galinha',0,16)
INSERT INTO TB_ALTERNATIVA VALUES ('Peixe',0,16)
INSERT INTO TB_ALTERNATIVA VALUES ('Girafa',1,16)
INSERT INTO TB_ALTERNATIVA VALUES ('Tartaura',0,16)


INSERT INTO TB_QUESTAO VALUES ('Qual é o maior animal terrestre?',5)
INSERT INTO TB_ALTERNATIVA VALUES  ('Elefante',1,17)
INSERT INTO TB_ALTERNATIVA VALUES ('Leão',0,17)
INSERT INTO TB_ALTERNATIVA VALUES ('Hipopótamo' ,0,17)
INSERT INTO TB_ALTERNATIVA VALUES ('Girafa',0,17)


INSERT INTO TB_QUESTAO VALUES ('Qual é o órgão responsável pela respiração nos seres humanos?',5)
INSERT INTO TB_ALTERNATIVA VALUES ('Coração',0,18)
INSERT INTO TB_ALTERNATIVA VALUES ('Estômago',0,18)
INSERT INTO TB_ALTERNATIVA VALUES ('Fígado',0,18)
INSERT INTO TB_ALTERNATIVA VALUES ('Pulmão',1,18)



INSERT INTO TB_QUESTAO VALUES ('Quais são as partes principais de um inseto?',5)
INSERT INTO TB_ALTERNATIVA VALUES ('Cabeça, tronco e membros',0,19)
INSERT INTO TB_ALTERNATIVA VALUES ('Cabeça, pescoço e pernas',0,19)
INSERT INTO TB_ALTERNATIVA VALUES ('Cabeça, tórax e abdômen',1,19)
INSERT INTO TB_ALTERNATIVA VALUES ('Cabeça, peito e barriga',0,19)


INSERT INTO TB_QUESTAO VALUES ('Qual é o processo pelo qual as plantas produzem seu próprio alimento?',6)
INSERT INTO TB_ALTERNATIVA VALUES ('Fotossíntese',1,20)
INSERT INTO TB_ALTERNATIVA VALUES  ('Respiração',0,20)
INSERT INTO TB_ALTERNATIVA VALUES  ('Digestão',0,20)
INSERT INTO TB_ALTERNATIVA VALUES  ('Circulação',0,20)






-- 


INSERT INTO TB_QUESTAO VALUES ('Qual é a forma geométrica que tem três lados?',2)
INSERT INTO TB_ALTERNATIVA VALUES ('Quadrado',0,21)
INSERT INTO TB_ALTERNATIVA VALUES  ('Círculo',0,21)
INSERT INTO TB_ALTERNATIVA VALUES  ('Triângulo',1,21)
INSERT INTO TB_ALTERNATIVA VALUES  ('Retângulo',0,21)


INSERT INTO TB_QUESTAO VALUES ('Quantos lados tem um retângulo?',2)
INSERT INTO TB_ALTERNATIVA VALUES ('2',0,22)
INSERT INTO TB_ALTERNATIVA VALUES  ('3',0,22)
INSERT INTO TB_ALTERNATIVA VALUES  ('4',1,22)
INSERT INTO TB_ALTERNATIVA VALUES  ('5',0,22)


INSERT INTO TB_QUESTAO VALUES ('Qual é a forma geométrica que tem quatro lados iguais?',2)
INSERT INTO TB_ALTERNATIVA VALUES ('Quadrado',1,   23)
INSERT INTO TB_ALTERNATIVA VALUES  ('Círculo',0,   23)
INSERT INTO TB_ALTERNATIVA VALUES  ('Triângulo',0, 23)
INSERT INTO TB_ALTERNATIVA VALUES  ('Retângulo',0, 23)


INSERT INTO TB_QUESTAO VALUES ('Quantos lados tem um pentágono?',2)
INSERT INTO TB_ALTERNATIVA VALUES  ('2',0,24)
INSERT INTO TB_ALTERNATIVA VALUES   ('3',0,24)
INSERT INTO TB_ALTERNATIVA VALUES   ('4',0,24)
INSERT INTO TB_ALTERNATIVA VALUES   ('5',1,24)


INSERT INTO TB_QUESTAO VALUES ('Qual é a forma geométrica que não possui lados?',2)
INSERT INTO TB_ALTERNATIVA VALUES ('Quadrado',0,   25)
INSERT INTO TB_ALTERNATIVA VALUES  ('Círculo',1,   25)
INSERT INTO TB_ALTERNATIVA VALUES  ('Triângulo',0, 25)
INSERT INTO TB_ALTERNATIVA VALUES  ('Retângulo',0, 25)


--

INSERT INTO TB_QUESTAO VALUES ('Qual é a parte da planta responsável pela absorção de água e nutrientes do solo?',6)
INSERT INTO TB_ALTERNATIVA VALUES  ('Folhas',0,   26)
INSERT INTO TB_ALTERNATIVA VALUES  ('Caule',0,   26)
INSERT INTO TB_ALTERNATIVA VALUES  ('Raiz',1,   26)
INSERT INTO TB_ALTERNATIVA VALUES  ('Flor',0,   26)


INSERT INTO TB_QUESTAO VALUES ('Quais são os produtos finais da fotossíntese?',6)
INSERT INTO TB_ALTERNATIVA VALUES  ('Oxigênio e glicose',1,   27)
INSERT INTO TB_ALTERNATIVA VALUES  ('Água e glicose',0,   27)
INSERT INTO TB_ALTERNATIVA VALUES  ('Dióxido de carbono e água',0,   27)
INSERT INTO TB_ALTERNATIVA VALUES  ('Oxigênio e dióxido de carbono',0,   27)


INSERT INTO TB_QUESTAO VALUES ('Quais são os principais fatores necessários para o crescimento saudável das plantas?',6)
INSERT INTO TB_ALTERNATIVA VALUES  ('Luz solar, água e solo fértil',1,   28)
INSERT INTO TB_ALTERNATIVA VALUES  ('Ventos fortes, luz solar e água salgada',0,   28)
INSERT INTO TB_ALTERNATIVA VALUES  ('Sombras, solo seco e ventilação',0,   28)
INSERT INTO TB_ALTERNATIVA VALUES  ('Fogo, chuva ácida e solo pedregoso',0,   28)



INSERT INTO TB_QUESTAO VALUES ('Como as plantas se reproduzem?',6)

INSERT INTO TB_ALTERNATIVA VALUES  ('Através de sementes',0,   29)
INSERT INTO TB_ALTERNATIVA VALUES  ('Através de ovos',0,       29)
INSERT INTO TB_ALTERNATIVA VALUES  ('Através de esporos',1,    29)
INSERT INTO TB_ALTERNATIVA VALUES  ('Através de filhotes',0,   29)

               

